#!/bin/bash
VOLUME=/data
ALLOW=${ALLOW:-192.168.0.0/16 172.16.0.0/12}
OWNER=${OWNER:-nobody}
GROUP=${GROUP:-nogroup}

chown "${OWNER}:${GROUP}" "${VOLUME}"
chown root /etc/rsyncd.passwd
chmod 600 /etc/rsyncd.passwd

[ -f /etc/rsyncd.conf ] || cat <<EOF > /etc/rsyncd.conf
uid = ${OWNER}
gid = ${GROUP}
use chroot = yes
pid file = /var/run/rsyncd.pid
log file = /dev/stdout

[volume]
    hosts deny = *
    hosts allow = ${ALLOW}
    read only = false
    path = ${VOLUME}
    comment = docker volume

[auth]
    path = ${VOLUME} 
    max connections = 15
    write only = yes
    list = no    
    ignore errors = yes
    timeout = 120
    auth users = ${USERNAME}
    secrets file = /etc/rsyncd.passwd

EOF

exec /usr/bin/rsync --no-detach --daemon --config /etc/rsyncd.conf "$@"
